Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWithUsers.Models;

namespace DemoWithUsers.Controllers
{
    public class AppsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Apps
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        public ActionResult AddToBasket(int? id)
        {
            if (Session[User.Identity.Name] == null)
            {
                Sessions temp = new Sessions
                {
                    UserEmail = User.Identity.Name,
                    Apps = new Dictionary<int, Product>()                 
                };

                if (!temp.Apps.ContainsKey((id.Value)))
                {
                    temp.Apps.Add(id.Value, db.Products.Find(id));

                    temp.TotalPrice += db.Products.Find(id).Price;
                    TempData["msg"] = "<script>alert('Denna app har lagts till i din appkorg!');</script>";
                }
                else
                    TempData["msg"] = "<script>alert('Denna app finns redan i din appkorg!');</script>";

                Session.Add(User.Identity.Name, temp);
            }
            else
            {
                Sessions temp = (Sessions)Session[User.Identity.Name];

                if (!temp.Apps.ContainsKey((id.Value)))
                {
                    temp.Apps.Add(id.Value, db.Products.Find(id));
                    temp.TotalPrice += db.Products.Find(id).Price;

                    TempData["msg"] = "<script>alert('Denna app har lagts till i din appkorg!');</script>";
                }
                else
                    TempData["msg"] = "<script>alert('Denna app finns redan i din appkorg!');</script>";

                Session[User.Identity.Name] = temp;
            }
            return RedirectToAction("Index");
        }

        // GET: Apps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Apps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Apps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price, ImageUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Apps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Apps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Apps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Apps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWithUsers.Models;

namespace DemoWithUsers.Controllers
{
    public class CartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            if (Session[User.Identity.Name] != null)
            {
                Sessions temp = (Sessions)Session[User.Identity.Name];

                List<Product> Carts = new List<Product>();

                foreach (var item in temp.Apps.Keys.ToList())
                    Carts.Add(db.Products.Find(item));

                return View(Carts.ToList());
            }
            else
            {
                Sessions temp = new Sessions
                {
                    UserEmail = User.Identity.Name,
                    Apps = new Dictionary<int, Product>()
                };

                Session.Add(User.Identity.Name, temp);
            }

            List<Product> Temp = new List<Product>();

            return View(Temp.ToList());


            /*
            //Vi kollar ifall det redan finns inkorg ala session
            if (Session["Cart"] == null)
                Session["Cart"] = new List<int>();

            //Skapar lista från session
            List<int> MyApps = new List<int>((List<int>)Session["Cart"]);
            */
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carts cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId")] Carts cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Carts cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId")] Carts cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            //Vi kollar ifall det finns en session först :P finns det inte = ingen varukorg = inga appar = ERROR :(
            if (Session[User.Identity.Name] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sessions temp = (Sessions)Session[User.Identity.Name];

            if (!temp.Apps.ContainsKey(id.Value))
            {
                return HttpNotFound();
            }

            return View();
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            /*
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            */

            if (Session[User.Identity.Name] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sessions temp = (Sessions)Session[User.Identity.Name];

            if (temp.Apps.ContainsKey(id))
                temp.Apps.Remove(id);

            temp.TotalPrice -= db.Products.Find(id).Price;

            //Ersätter gamla med nya uppdaterade session
            Session.Add(User.Identity.Name, temp);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/WishesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWithUsers.Models;

namespace DemoWithUsers.Controllers
{
    public class WishesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Wishes
        public ActionResult Index()
        {
            List<Product> Apps = new List<Product>();

            if (Session[User.Identity.Name] == null)
            {
                Sessions temp = new Sessions
                {
                    UserEmail = User.Identity.Name,
                    Apps = new Dictionary<int, Product>()
                };

                Session.Add(User.Identity.Name, temp);
            }

            //hitta alla tabeller i wishes som tillhör dig ala samma email :O
            foreach (var item in db.Wishes.Where(x => x.UserIdentity == User.Identity.Name).ToList())
            {
                //då vi har fått fram id från varje wishes där email stämmer med inloggade
                Product app = db.Products.Find(item.AppId);

                //extra kontroll + lägger till i listan som vi skickar till vyn :D
                if (app != null)
                    if (!Apps.Contains(app))
                        Apps.Add(app);
            }

            return View(Apps.ToList());
        }

        public ActionResult AddToBasket(int? id)
        {

            Wish wish = db.Wishes.Find(id);

            //ifall wish är null betyder vi ej har appen i listan
            if (wish == null)
            {
                wish = new Wish
                {
                    AppId = id.Value,
                    UserIdentity = User.Identity.Name
                };

                db.Wishes.Add(wish);
                db.SaveChanges();

                TempData["msg"] = "<script>alert('Denna app har lagts till i din önskelista!');</script>";
            }
            else
            {
                TempData["msg"] = "<script>alert('Denna app finns redan i din önskelista!');</script>";
            }

            return RedirectToAction("Details", "Apps", new {id = id.Value });
        }

        // GET: Wishes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Vi går direkt till appvyn istället
            return RedirectToAction("Details", "Apps", new { id = id.Value });
        }

        // GET: Wishes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Wishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserIdentity,AppId")] Wish wish)
        {
            if (ModelState.IsValid)
            {
                db.Wishes.Add(wish);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wish);
        }

        // GET: Wishes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wish wish = db.Wishes.Find(id);
            if (wish == null)
            {
                return HttpNotFound();
            }
            return View(wish);
        }

        // POST: Wishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserIdentity,AppId")] Wish wish)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wish).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wish);
        }

        // GET: Wishes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product wish = db.Products.Find(id);

            return View(wish);
        }

        // POST: Wishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wish wish = new Wish();

            //lite jobbigt men vi behöver loopa igenom alla för det är appid och inte unika idn..
            foreach (var item in db.Wishes.Where(x => x.UserIdentity == User.Identity.Name).ToList())
            {
                //vi kollar så det är appen vi söker
                if (item.AppId == id)
                {
                    //får fram wishobjektet med rätt id nu
                    wish = db.Wishes.Find(item.Id);
                    if (wish != null)
                        break; //avslutar loopen då vi hittat
                }
            }

            db.Wishes.Remove(wish);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
@using DemoWithUsers.Models

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Latest compiled and minified CSS -->
    @*@Styles.Render("//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css")
    @Scripts.Render("//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js")*@
</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("App Store", "Index", "Apps", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Hem", "Index", "Apps")</li>

                    @*Du måste va inloggad för att se dessa flikar ;)*@
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Appar <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Min önskelista", "Index", "Wishes")</li>
                                <li>@Html.ActionLink("Mina appar", "Index", "OrderDetails")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="@Url.Action("Index", "Carts")">
                                Kundvagn
                                <span class="badge badge-primary" id="countcart">
                                    @{
                                        @Html.Display("0")

                                        Sessions temp = (Sessions)Session[User.Identity.Name];
                                        if (temp != null)
                                        {
                                            @temp.Apps.Count
                                        }
                                    }
                                </span>
                            </a>
                        </li>
                    }

                    @*är du admin :O*@
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Alla appar", "Index", "Products")</li>
                                <li>@Html.ActionLink("Lägg till appar", "Create", "Products")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Alla köp", "Index", "OrderDetailsAdmin")</li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <br />

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/custom.js")
    @RenderSection("scripts", required: false)
</body>
</html>