Models/OrderDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DemoWithUsers.Models
{
    public class OrderDetail
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Ordernummer")]
        public int OrderId { get; set; }

        [Required]
        [Display(Name = "Namn")]
        public string Firstname { get; set; }

        [Required]
        [Display(Name = "Efternamn")]
        public string Lastname { get; set; }

        [Required]
        [Display(Name = "Adress")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Postkod")]
        public int PostalCode { get; set; }

        [Required]
        [Display(Name = "Ort")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Mobilnummer")]
        public int PhoneNumber { get; set; }
    }
}

Models/OrderDetailViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DemoWithUsers.Models
{
    public class OrderDetailViewModels
    {
        //så vi kan få med totalprice :D

        public int Id { get; set; }

        [Display(Name = "Ordernummer")]
        public int OrderId { get; set; }

        [Display(Name = "Namn")]
        public string Firstname { get; set; }

        [Display(Name = "Efternamn")]
        public string Lastname { get; set; }

        [Display(Name = "Adress")]
        public string Address { get; set; }

        [Display(Name = "Postkod")]
        public int PostalCode { get; set; }

        [Display(Name = "Ort")]
        public string City { get; set; }

        [Display(Name = "Mobilnummer")]
        public int PhoneNumber { get; set; }

        [Display(Name = "Totalt pris")]
        public double TotalPrice { get; set; }

        [Display(Name = "Konto")]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "App")]
        public List<Product> Apps { get; set; }
    }
}

Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWithUsers.Models;

namespace DemoWithUsers.Controllers
{
    public class AppsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Apps
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        public ActionResult AddToBasket(int? id)
        {
            if (Session[User.Identity.Name] == null)
            {
                Sessions temp = new Sessions
                {
                    UserEmail = User.Identity.Name,
                    Apps = new Dictionary<int, Product>()                 
                };

                if (!temp.Apps.ContainsKey((id.Value)))
                {
                    temp.Apps.Add(id.Value, db.Products.Find(id));

                    temp.TotalPrice += db.Products.Find(id).Price;
                    TempData["msg"] = "<script>alert('Denna app har lagts till i din appkorg!');</script>";
                }
                else
                    TempData["msg"] = "<script>alert('Denna app finns redan i din appkorg!');</script>";

                Session.Add(User.Identity.Name, temp);
            }
            else
            {
                Sessions temp = (Sessions)Session[User.Identity.Name];

                if (!temp.Apps.ContainsKey((id.Value)))
                {
                    temp.Apps.Add(id.Value, db.Products.Find(id));
                    temp.TotalPrice += db.Products.Find(id).Price;

                    TempData["msg"] = "<script>alert('Denna app har lagts till i din appkorg!');</script>";
                }
                else
                    TempData["msg"] = "<script>alert('Denna app finns redan i din appkorg!');</script>";

                Session[User.Identity.Name] = temp;
            }
            return RedirectToAction("Index");
        }

        // GET: Apps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Apps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Apps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price, ImageUrl")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Apps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Apps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Apps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Apps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemoWithUsers.Models;

namespace DemoWithUsers.Controllers
{
    public class OrderDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: OrderDetails
        public ActionResult Index()
        {
            List<OrderDetailViewModels> OrderDetailsViews = new List<OrderDetailViewModels>();

            foreach (var item in db.OrderDetails.ToList())
            {
                if (item != null)
                {
                    //så vi bara listar rätt persons ordrar, vi kollar samma email från session + ordermodellen ;)
                    if (User.Identity.Name == db.Orders.Where(x => x.OrderId == item.OrderId).FirstOrDefault().UserIdentity)
                    {
                        OrderDetailViewModels temp = new OrderDetailViewModels
                        {
                            Id = item.Id,
                            Firstname = item.Firstname,
                            Lastname = item.Lastname,
                            OrderId = item.OrderId,
                            PhoneNumber = item.PhoneNumber,
                            PostalCode = item.PostalCode,
                            Address = item.Address,
                            City = item.City,
                            Email = db.Orders.Where(x => x.OrderId == item.OrderId).FirstOrDefault().UserIdentity,

                            //så vi får fram totalprice från tabellen orders till vår vymodell som ärvt från OrderDetail :D
                            TotalPrice = db.Orders.Where(x => x.OrderId == item.OrderId).FirstOrDefault().OrderTotalPrice
                        };

                        //Sparar objektet i listan som vi sedan skickar till vyn med TotalPrice :D
                        OrderDetailsViews.Add(temp);
                    }
                }
            }

            return View(OrderDetailsViews.ToList());
        }

        // GET: OrderDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            OrderDetail orderDetail = db.OrderDetails.Find(id);
            OrderDetailViewModels temp = new OrderDetailViewModels
            {
                Apps = new List<Product>()
            };

            //använder orderdetailviewmodels så vi kan få fram totalprice också
            if (orderDetail != null)
            {

                temp.Id = orderDetail.Id;
                temp.Firstname = orderDetail.Firstname;
                temp.Lastname = orderDetail.Lastname;
                temp.OrderId = orderDetail.OrderId;
                temp.PhoneNumber = orderDetail.PhoneNumber;
                temp.PostalCode = orderDetail.PostalCode;
                temp.Address = orderDetail.Address;
                temp.City = orderDetail.City;

                //så vi får fram totalprice från tabellen orders till vår vymodell som ärvt från OrderDetail :D
                temp.TotalPrice = db.Orders.Where(x => x.OrderId == orderDetail.OrderId).FirstOrDefault().OrderTotalPrice;

                foreach (var dbItem in db.OrderItems.ToList())
                {
                    if (dbItem.OrderId == orderDetail.OrderId)
                    {
                        Product pro = db.Products.Find(dbItem.AppId);
                        temp.Apps.Add(pro);
                    }
                }
            }

            //ingen orderdetail, kunde ej hitta ordern så vi skickar errorpage
            if (temp == null)
                return HttpNotFound();

            return View(temp);
        }

        // GET: OrderDetails/Create
        public ActionResult Create()
        {
            OrderDetailViewModels orderDetailViews = new OrderDetailViewModels();
            Product product;

            if (Session[User.Identity.Name] == null)
            {
                return RedirectToAction("Index", "Carts");
            }
            else
            {
                Sessions temp = (Sessions)Session[User.Identity.Name];

                //Vi har noll appar, varför skapa order då? :O
                if (temp.TotalPrice == 0)
                    return RedirectToAction("Index", "Carts");

                orderDetailViews.TotalPrice = temp.TotalPrice;
                orderDetailViews.Apps = new List<Product>();

                //Loopar igenom apparna vi har från session -> appkorg
                foreach (var item in temp.Apps.Keys.ToList())
                {
                    //sparar appen i ett temp-objekt
                    product = db.Products.Find(item);

                    //extra kontroll
                    if (product != null)
                    {
                        //denna är onödig egentligen då jag inte kodat cache som lever under programmets gång men saksamma, redan kodat detta så behåller det
                        //nu lägger vi in appen i vårt orderobjekt så vi kan spara ordern i databasen, extrakontroll bara innan vi lägger till
                        if (!orderDetailViews.Apps.Contains(product))
                        {
                            //lägger till appen i cache samt orderItem objekt som sparas vidare i databasen sen ifall cachen försvinner
                            orderDetailViews.Apps.Add(product);
                        }
                    }
                }
            }

            return View(orderDetailViews);
        }


        // GET: OrderDetails/Create
        public ActionResult Checkout()
        {
            OrderDetailViewModels orderDetailViews = new OrderDetailViewModels();
            Product product;

            if (Session[User.Identity.Name] == null)
            {
                return RedirectToAction("Index", "Carts");
            }
            else
            {
                Sessions temp = (Sessions)Session[User.Identity.Name];

                //Vi har noll appar, varför skapa order då? :O
                if (temp.TotalPrice == 0)
                    return RedirectToAction("Index", "Carts");

                orderDetailViews.TotalPrice = temp.TotalPrice;
                orderDetailViews.Apps = new List<Product>();

                //Loopar igenom apparna vi har från session -> appkorg
                foreach (var item in temp.Apps.Keys.ToList())
                {
                    //sparar appen i ett temp-objekt
                    product = db.Products.Find(item);

                    //extra kontroll
                    if (product != null)
                    {
                        //denna är onödig egentligen då jag inte kodat cache som lever under programmets gång men saksamma, redan kodat detta så behåller det
                        //nu lägger vi in appen i vårt orderobjekt så vi kan spara ordern i databasen, extrakontroll bara innan vi lägger till
                        if (!orderDetailViews.Apps.Contains(product))
                        {
                            //lägger till appen i cache samt orderItem objekt som sparas vidare i databasen sen ifall cachen försvinner
                            orderDetailViews.Apps.Add(product);
                        }
                    }
                }
            }

            return View(orderDetailViews);
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OrderId,Firstname,Lastname,Address,PostalCode,City,PhoneNumber")] OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                if (Session[User.Identity.Name] != null)
                {
                    OrderDetailViewModels orderDetailViews = new OrderDetailViewModels();
                    Sessions temp = (Sessions)Session[User.Identity.Name];

                    //Generera vår unika id, inte bästa sättet men orkade ej byta alla int till sträng när jag såg guid generator
                    int Id = new Random().Next();
                    Product product;

                    orderDetail.Id = Id; //vet ej varför men blir error utan? :S
                    orderDetail.OrderId = Id;

                    //jobbigt men vi måste göra en kopia av vyn för kvitto som innehåller applista
                    orderDetailViews.Id = Id;
                    orderDetailViews.OrderId = Id;
                    orderDetailViews.Firstname = orderDetail.Firstname;
                    orderDetailViews.Lastname = orderDetail.Lastname;
                    orderDetailViews.Address = orderDetail.Address;
                    orderDetailViews.PostalCode = orderDetail.PostalCode;
                    orderDetailViews.City = orderDetail.City;
                    orderDetailViews.PhoneNumber = orderDetail.PhoneNumber;
                    orderDetailViews.Apps = new List<Product>();

                    //Vi måste spara varje app i databasen, går ju inte att spara lista i ett fält i databasen :O
                    OrderItem orderItem = new OrderItem
                    {
                        OrderId = Id
                    };

                    //Ny order, här sparar vi info om själva ordern, datum, totalpris m.m, denna behövs inte heller bara om vi skulle cacha allt i en lista som går igenom hela programmet
                    OrderViewModels orderViews = new OrderViewModels
                    {
                        OrderTotalPrice = temp.TotalPrice,
                        UserIdentity = User.Identity.Name,
                        OrderId = Id,
                        Apps = new List<int>()
                    };

Views/OrderDetails/Checkout.cshtml
@model DemoWithUsers.Models.OrderDetailViewModels

@{
    ViewBag.Title = "Checkout";
}

<h2>Tack för ditt köp!</h2>

<div>
    <h4>Information om ditt köp</h4>
    <a href="@Url.Action("Index", "Apps")" class="btn btn-default">
        Tillbaka
    </a>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>

@foreach (var item in Model.Apps)
{
    <div class="col-md-4">
        <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
        <p>@Html.DisplayFor(modelItem => item.Desc)</p>
        <img src="@Url.Content(item.ImageUrl)" alt="@item.Name" />
        <br /><br /><b>@Html.DisplayFor(modelItem => item.Price) kr</b><br /><br />
    </div>
}

Views/OrderDetails/Create.cshtml
@model DemoWithUsers.Models.OrderDetailViewModels

@{
    ViewBag.Title = "Create";
}

<br /><br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Skapa beställning</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <b>Totalt: <font color="green">@Html.DisplayFor(modelItem => Model.TotalPrice)</font> kr</b>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <input type="submit" value="Beställ" class="btn btn-success" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-7">
                <a href="@Url.Action("Index", "Carts")" class="btn btn-danger">
                    Avbryt
                </a>
            </div>
        </div>
    </div>
}

@foreach (var item in Model.Apps)
{
    <div class="col-md-4">
        <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
        <p>@Html.DisplayFor(modelItem => item.Desc)</p>
        <img src="@Url.Content(item.ImageUrl)" alt="@item.Name" />
        <br /><br /><b>@Html.DisplayFor(modelItem => item.Price) kr</b><br /><br />
        <a href="@Url.Action("Delete", "Carts", new { id = item.Id } )" class="btn btn-danger">
            Ta bort
        </a>
    </div>
}

Views/OrderDetails/Details.cshtml
@model DemoWithUsers.Models.OrderDetailViewModels

@{
    ViewBag.Title = "Details";
}

<h2>Orderinfo</h2>

<div>
    <h4>Uppgifter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dd>
            @foreach (var item in Model.Apps)
        {
            <center>
                <div class="col-md-4">
                    <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
                    <p>@Html.DisplayFor(modelItem => item.Desc)</p>
                    <img src="@Url.Content(item.ImageUrl)" alt="@item.Name" />
                    <br /><br /><b>@Html.DisplayFor(modelItem => item.Price) kr</b><br /><br />
                </div>
            </center>
    }
        </dd>
    </dl>
</div>
<p>
    <a href="@Url.Action("Index", "OrderDetails")" class="btn btn-default">Tillbaka</a>
</p>

Views/OrderDetails/Edit.cshtml
@model DemoWithUsers.Models.OrderDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>OrderDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "OrderDetails")" class="btn btn-default">Tillbaka</a>
</div>

Views/OrderDetails/Index.cshtml
@model IEnumerable<DemoWithUsers.Models.OrderDetailViewModels>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Kontakta oss", "Contact", "Home")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lastname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostalCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Firstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lastname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            <a href="@Url.Action("Details", "OrderDetails", new { id = item.Id })" class="btn btn-warning">Mer information</a>
        </td>
    </tr>
}

</table>